### ISSUE TITLE
Login SignUp Page

### ISSUE THREAD

**Issue by anshajsharma** [anshajsharma/donation-app-frontend#6]
- Login
  - UserName 
  - Pass
- Signup
  - Individual or Organisation
  - Name
  - DOB(I) , DOE(O)
  - Etc. (Contact Backend Team for User Schema)

**Comment by Siren001** [comment]
Sir I would like to take up this issue (Arya)

**Comment by Aman12305** [comment]
Sir I would like to take up this issue Aman

**Comment by singhdivyaanshu** [comment]
Sir I would like to take this issue !
